### ISSUE TITLE
Customizing position and display

### ISSUE THREAD

**Issue by Saumya-Bhatt** [samdobson/streamlit-metrics#1]
Seriously, this was a much needed feature in Streamlit and the one you have made looks (and works!) absolutely gorgeous! However, I was thinking if there could be more customizability that could be added to this widget maybe? I was thinking of:

1.  Ability to change the size of the value. 
2. Ability to change the font of the nameplate of that value. For example, it could be options from [bold, italics] but if one is adventurous, could also allow fonts from external sources (google fonts maybe?)
3. Currently, I am only able to add the widget to the main page. If it could be done for the sidebar as well, that would be awesome!

Overall, I was thinking of maybe, the final method would look like:

```
value_dict =     {
        "METRIC 1": 100,
        "METRIC 2": 200,
        "METRIC 3": 300,
        "METRIC 4": 400,
    }

custom_font = 'https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap'
```
The font one can also be a list of inbuilt options such as [ Bold, Italian ]. The final call could look like this:
```
metric_row(data=value_dict, font_size=42, sidebar=True, font=custom_font)
```

The best possible way would be to integrate this widget into the `st.empty()` element. As that would at least take care of the sidebar customization.  Nonetheless, great job!!

**Comment by samdobson** [comment]
Hi @Saumya-Bhatt,

Thanks for the feedback!

Custom size and font is certainly doable and definitely agree this would be a good addition. I'm eagerly awaiting Streamlit core's theming support to be able to define a consistent look across an application - it may be that once this is ready, we can tap into this. In the meantime, I'm happy to accept PRs to implement this functionality, and failing that, will hopefully get to this on a rainy day!

Regarding adding the component to the sidebar, have you tried this? (untested)

```python
with st.sidebar:
    metric('Sidebar Metric', 1)
```

**Comment by Saumya-Bhatt** [comment]
Whoa, that worked! Until 2 metrics, it is working well. However, the elements are all getting squeezed up for adding any more metrics. I guess changing it won't be that much difficult (will try to issue a PR for that). This is how it is looking for my project.

![Screenshot 2020-11-10 233049](https://user-images.githubusercontent.com/46018242/98712987-067b7280-23ad-11eb-83fd-6946c772a86e.jpg)

I had a small doubt. If I wanted to dynamically change the contents of the metric_row(), how to go about it? I understand that one can do 
```
metrics = st.empty()
def update_value_periodically():
    temp = get_new_values()
    metrics.metric_row(temp)
    time.sleep(1)
    metrics.empty()
```

The update_value_periodically can be scheduled to run every 1s so as to achieve almost near-time updates. I tried doing the above but it gave the error `empty() has no method metric_row`. I guess that was expected, but is there a workaround to this or any other way to do that?

Thanks a lot for the reply!

**Comment by samdobson** [comment]
To dynamically change the contents, rather than try to update the ``metric_row` object, you can simply update the dictionary:

```python
temp = {'Old data': 0}
metric_row(temp)
temp = {'New data': 1}
```

The periodic refresh part is outside the scope of this component. For what it's worth, I don't think your proposed approach will work unfortunately - calling`time.sleep()` will simply delay loading of the app. Streamlit does not have a built-in way to do periodic re-runs, but perhaps as a suggestion you could look into doing something like this: https://discuss.streamlit.io/t/periodic-app-update/3075

**Comment by samdobson** [comment]
I'm not sure that custom components are compatible with `st.empty()` unfortunately. The Streamlit devs on the forum would probably be best to confirm.

The periodic refresh part is outside the scope of this component, but for what it's worth, I don't think your proposed approach will work unfortunately - calling`time.sleep()` will simply delay loading of the app. Streamlit does not have a built-in way to do periodic re-runs, but perhaps as a suggestion you could look into doing something like this: https://discuss.streamlit.io/t/periodic-app-update/3075

**Comment by samdobson** [comment]
I'm closing all issues and PRs, and archiving the repo, because an enhanced version of the metrics component is now part of Streamlit core: https://share.streamlit.io/streamlit/release-demos/0.87/0.87
