### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by Jorgvt** [samdobson/streamlit-metrics#2]
Hi! 

First of all, congrats on the awesome feature you built ^^

I was wondering if you can change the color of the text and numbers, because when using a dark theme it gets hard to read the black numbers.

Thank you very much!

**Comment by Jorgvt** [comment]
Actually I was able to do it modifying the _build_metric function and adding a color parameter like:
```.metric {
       font-family: "IBM Plex Sans", sans-serif;
       text-align: center;
       color: white;
    }
```
It would be nice though if it could be dinamically changed depending on the theme of the page, I'll keep looking into it ^^

**Comment by yeshwanth1312** [comment]
Any easy way to make this work for dark mode? Right now all things are black 

![Sample screenshot](https://user-images.githubusercontent.com/34922578/123968433-35b71200-d985-11eb-99f8-221dfd2e8dd6.jpg)

**Comment by Jorgvt** [comment]
@yeshwanth1312 if you edit the `__init__.py` file and add the `color: <color you want>` parameter in the `_build_metric()_` function (as I did in my previous comment) you can display the color you want, but it's not dynamic with the theme.

> Actually I was able to do it modifying the _build_metric function and adding a color parameter like:
> 
> ```
>        font-family: "IBM Plex Sans", sans-serif;
>        text-align: center;
>        color: white;
>     }
> ```
> 
> It would be nice though if it could be dinamically changed depending on the theme of the page, I'll keep looking into it ^^

**Comment by samdobson** [comment]
Hey,

Thanks for the report. I'm closing all issues and PRs, and archiving the repo, because an enhanced version of the metrics component is now part of Streamlit core: https://share.streamlit.io/streamlit/release-demos/0.87/0.87
