### ISSUE TITLE
Changing function from beta phase 

### ISSUE THREAD

**Issue by 100mi** [samdobson/streamlit-metrics#3]
### Problem 

The st.beta_columns() will graduate from streamlit sooner and will be replaced with st.columns
The given warning in streamlit is refered as :
<img width="1298" alt="Screenshot 2021-08-13 at 11 45 14 AM" src="https://user-images.githubusercontent.com/63118329/129313292-f416fab7-3c2d-4458-829a-49646cc41f99.png">

### Solution 

1. Inside your `__init__.py` change function from `st.beta_columns` to `st.columns`.
2. For more information refer to [streamlit API documentation](https://docs.streamlit.io/en/stable/api.html#streamlit.columns)

**Comment by samdobson** [comment]
Hey,

Thanks for the report. I'm closing all issues and PRs, and archiving the repo, because an enhanced version of the metrics component is now part of Streamlit core: https://share.streamlit.io/streamlit/release-demos/0.87/0.87
